### ISSUE TITLE
If the window is scrolled vertically, mouse presses are misaligned

### ISSUE THREAD

**Issue by ensurdagen** [Patashu/Combo-Priest-Simulator#2] opened 2018-12-21 20:23 UTC
I just tried to start the simulator and it does not work in any of my browsers since the update. Clicking start or puzzles does nothing. Are older versions available anywhere?

**Comment by Patashu** [comment] 2018-12-21 20:58
I am unable to reproduce on Windows 10. I have tried Chrome and Firefox and Edge. Can you do the following things, please:

1) Hard refresh (Ctrl+F5).
2) Ensure that the browser window is large enough to hold the whole screen vertically and horizontally. (There is currently a bug that misaligns mouse clicks if this is not the case, I haven't investigated further yet.)
3) Report what browser/OS combinations fail and work after trying these troubleshooting steps. For each one that doesn't work, use Right click -> Inspect and report if any errors have appeared in the Console.

You can download older versions by doing e.g. https://github.com/Patashu/Combo-Priest-Simulator/tree/577eebfd3bbc6fadff701c2829a8a8495511928a but you will need to be able to run it as a web server to play it locally.

Thanks!

**Comment by ensurdagen** [comment] 2018-12-21 22:04
Resizing the window worked! Thank you!

**Comment by Patashu** [comment] 2018-12-21 22:04
Thanks! I'll rename this issue and leave it open until I've looked at it.

**Comment by Patashu** [comment] 2018-12-21 23:03
Fixed by v1.05, thanks for the report!

**Closed as completed by Patashu** 2018-12-21 23:03 UTC
